import { useMutation, useQuery } from "@tanstack/react-query";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { json } from "stream/consumers";
import TextArea from "../components/TextArea";
import Button from "../components/Button";
import styles from "../styles/Home.module.css";
import { Prompt } from "./api/prompts";
import { useState } from "react";
import PromptList from "../components/PromptList";

const Home: NextPage = () => {
  const [prompt, setPrompt] = useState("");

  const { data, isLoading, error, refetch } = useQuery(
    ["prompts"],
    fetchPrompts
  );

  function fetchPrompts(): Promise<Prompt[]> {
    return fetch("/api/prompts").then((res) => res.json());
  }

  const {
    mutate,
    data: savePromptData,
    isLoading: isPosting,
  } = useMutation(["prompt"], savePrompt);

  function savePrompt(): Promise<Prompt> {
    return fetch("/api/prompt", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ prompt }),
    }).then((res) => {
      refetch();
      return res.json();
    });
  }

  console.log(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Prompt Store</h1>

        <p className={styles.description}>Store your favorite prompts!</p>
        <TextArea onChange={handlePromptChange} />
        <Button onClick={() => mutate()} />

        {data && data.length > 0 && <PromptList prompts={data} />}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );

  function handlePromptChange(prompt: string) {
    setPrompt(prompt);
  }
};

export default Home;
