import { useMutation, useQuery } from '@tanstack/react-query';
import Head from 'next/head';
import type { NextPage } from 'next';

import { Prompt } from './api/prompts';
import PromptForm from '../components/common/PromptForm';
import PromptList from '../components/common/PromptList';
import TopBar from '../components/common/TopBar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { data, refetch } = useQuery(['prompts'], fetchPrompts);
  const { mutate: savePromptMutate } = useMutation(['prompt'], savePrompt);

  function fetchPrompts(): Promise<Prompt[]> {
    return fetch('/api/prompts').then((res) => res.json());
  }

  function savePrompt(prompt: string): Promise<Prompt> {
    return fetch('/api/prompt', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ prompt }),
    }).then((res) => {
      refetch();
      return res.json();
    });
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <main className="container">
        <h1 className={styles.title}>Prompt Store</h1>

        <p className={styles.description}>Store your favorite prompts!</p>
        <PromptForm onSubmit={handlePromptSubmit} />
        {data && data.length > 0 && (
          <section className="mt-8">
            <PromptList prompts={data} />
          </section>
        )}
      </main>

      <footer className={'mt-8 border-t-2 border-slate-600 text-center pt-2'}>
        By Laurence Juden
      </footer>
    </div>
  );

  function handlePromptSubmit(prompt: string) {
    savePromptMutate(prompt);
  }
};

export default Home;
